version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:18.03.1-ce-git
        environment:
          RELEASE_SERIES_LIST: "1.14"
          LATEST_STABLE: "1.14"
          DISTRIBUTIONS_LIST: "debian-9,ol-7,rhel-7"
          IMAGE_NAME: nginx
          CHART_NAME: nginx
          CHART_REPO: https://github.com/bitnami/charts
          DOCKER_PROJECT: bitnami
          QUAY_PROJECT: bitnami
          GCLOUD_PROJECT: bitnami-containers
          AZURE_PROJECT: bitnami

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.03.1-ce
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl bash coreutils
      - run:
          name: Docker info
          command: |
            docker version
            docker info
      - deploy:
          name: Publish docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              curl -sL https://raw.githubusercontent.com/bitnami/test-infra/master/circle/docker-release-image.sh | bash -
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*(?<!-rhel-7)-r[0-9]+$/
