version: '2'

services:
  nginx:
    image: 'bitnami/nginx:1'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'nginx_data:/bitnami/nginx'

volumes:
  nginx_data:
    driver: local
